name: Create Archive
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Archive code
        run: |
          version=$(date +'%y-%m-%d-%H-%M')
          git archive --format=zip HEAD -o $version.zip
      - name: Publish archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: ${{ env.version }}.zip
